# Generated by Django 4.2.21 on 2025-06-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('units_sold', models.IntegerField()),
                ('revenue', models.DecimalField(decimal_places=3, max_digits=15)),
                ('operating_profit', models.DecimalField(decimal_places=3, max_digits=15)),
                ('roi', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FactCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=255)),
                ('units_sold', models.IntegerField()),
                ('revenue', models.DecimalField(decimal_places=3, max_digits=15)),
                ('operating_profit', models.DecimalField(decimal_places=3, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='FactSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('retailer', models.CharField(max_length=100)),
                ('sales_method', models.CharField(max_length=50)),
                ('units_sold', models.IntegerField()),
                ('revenue', models.DecimalField(decimal_places=3, max_digits=15)),
                ('operating_profit', models.DecimalField(decimal_places=3, max_digits=15)),
            ],
        ),
    ]
